<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px" />

# Pandas — Comprehensive Lab

### Topics covered
1. Creating DataFrames and data summary
2. Selecting rows and columns
3. Data types and type casting
4. Datetime conversion and `dt` attributes
5. Creating, renaming, and removing columns
6. Unique values and value counts
7. Missing values
8. Resetting indexes
9. Duplicated values

**Instructions:** Each exercise provides its own sample data. You do not need the `orders` dataset or an external CSV file.

# Section I: Creating DataFrames and Data Summary

1) Import the pandas library using the alias `pd`. Then create the DataFrame below and save it as `students`.

```python
{
    'student_id': [101, 102, 103, 104, 105],
    'name': ['Ali', 'Noor', 'Sara', 'Omar', 'Maya'],
    'score': [88, 92, 79, 85, 95],
    'city': ['Manama', 'Riffa', 'Manama', 'Muharraq', 'Riffa']
}
```

In [2]:
import pandas as pd

students = pd.DataFrame({
    'student_id': [101, 102, 103, 104, 105],
    'name': ['Ali', 'Noor', 'Sara', 'Omar', 'Maya'],
    'score': [88, 92, 79, 85, 95],
    'city': ['Manama', 'Riffa', 'Manama', 'Muharraq', 'Riffa']
    })

students

   student_id  name  score      city
0         101   Ali     88    Manama
1         102  Noor     92     Riffa
2         103  Sara     79    Manama
3         104  Omar     85  Muharraq
4         105  Maya     95     Riffa

2) Display the first 3 rows of `students`.

In [3]:
students[0:3]

   student_id  name  score    city
0         101   Ali     88  Manama
1         102  Noor     92   Riffa
2         103  Sara     79  Manama

3) Display the last 2 rows of `students`.

In [4]:
students.tail(2)

   student_id  name  score      city
3         104  Omar     85  Muharraq
4         105  Maya     95     Riffa

4) Use `.sample()` to display 2 random rows from `students`.

In [5]:
students.sample(2)

   student_id  name  score    city
0         101   Ali     88  Manama
1         102  Noor     92   Riffa

5) Display the number of rows and columns in `students`, then display its column names.

In [6]:
students.shape

(5, 4)

6) Use `.info()` to inspect the columns, non-null values, and data types in `students`.

In [7]:
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  5 non-null      int64
 1   name        5 non-null      str
 2   score       5 non-null      int64
 3   city        5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

7) Generate descriptive statistics for the numerical columns in `students`.

In [8]:
students.describe()

       student_id      score
count    5.000000   5.000000
mean   103.000000  87.800000
std      1.581139   6.220932
min    101.000000  79.000000
25%    102.000000  85.000000
50%    103.000000  88.000000
75%    104.000000  92.000000
max    105.000000  95.000000

# Section II: Selecting Rows and Columns

8) Create this DataFrame and save it as `employees`.

```python
{
    'employee_id': [201, 202, 203, 204, 205, 206],
    'name': ['Ahmed', 'Fatima', 'Hassan', 'Maryam', 'Yousef', 'Layla'],
    'department': ['Finance', 'IT', 'HR', 'IT', 'Finance', 'HR'],
    'salary': [850, 1100, 900, 1250, 980, 1050]
}
```

Select only the `name` column.

In [9]:
employees =pd.DataFrame({
    'employee_id': [201, 202, 203, 204, 205, 206],
    'name': ['Ahmed', 'Fatima', 'Hassan', 'Maryam', 'Yousef', 'Layla'],
    'department': ['Finance', 'IT', 'HR', 'IT', 'Finance', 'HR'],
    'salary': [850, 1100, 900, 1250, 980, 1050]
})

employees['name']

0     Ahmed
1    Fatima
2    Hassan
3    Maryam
4    Yousef
5     Layla
Name: name, dtype: str

9) From `employees`, select the `name` and `salary` columns.

In [10]:
employees[['name', 'salary']]

     name  salary
0   Ahmed     850
1  Fatima    1100
2  Hassan     900
3  Maryam    1250
4  Yousef     980
5   Layla    1050

10) Display rows at positions 1 through 3 from `employees`.

In [11]:
employees[1:4]

   employee_id    name department  salary
1          202  Fatima         IT    1100
2          203  Hassan         HR     900
3          204  Maryam         IT    1250

11) Using `.loc`, return the `department` value at index label `3`.

In [12]:
employees.loc[3, "department"]

'IT'

12) Using `.loc`, select rows with index labels `1` and `4` and display only `name` and `salary`.

In [13]:
employees.loc[[1,4], ['name', 'salary']]

     name  salary
1  Fatima    1100
4  Yousef     980

13) Using `.iloc`, select the row at position `2` and the columns at positions `1` and `3`.

In [14]:
employees.iloc[2, [1,3]]

name      Hassan
salary       900
Name: 2, dtype: object

# Section III: Data Types and Dates

14) Create the DataFrame below as `sales`.

```python
{
    'invoice': ['A101', 'A102', 'A103', 'A104'],
    'quantity': ['5', '8', '3', '10'],
    'sale_date': ['2026-01-15', '2026-02-20', '2026-03-10', '2026-04-05']
}
```

Display the data type of every column.

In [15]:
sales = pd.DataFrame({
    'invoice': ['A101', 'A102', 'A103', 'A104'],
    'quantity': ['5', '8', '3', '10'],
    'sale_date': ['2026-01-15', '2026-02-20', '2026-03-10', '2026-04-05']
})

sales.dtypes

invoice      str
quantity     str
sale_date    str
dtype: object

15) Convert `quantity` from text to integer.

In [16]:
sales['quantity'] = sales['quantity'].astype(int)

16) Convert `sale_date` to pandas datetime format.

In [17]:
sales['sale_date'] = pd.to_datetime(sales['sale_date'])
sales.dtypes

invoice                 str
quantity              int64
sale_date    datetime64[us]
dtype: object

17) Create a new column called `sale_year` by extracting the year from `sale_date`.

In [18]:
sales['sales_year'] = sales['sale_date'].dt.year
sales.dtypes

invoice                  str
quantity               int64
sale_date     datetime64[us]
sales_year             int32
dtype: object

18) Create a new column called `sale_month` containing the full month name from `sale_date`.

In [19]:
sales['sale_month'] = sales['sale_date'].dt.month_name()
sales

  invoice  quantity  sale_date  sales_year sale_month
0    A101         5 2026-01-15        2026    January
1    A102         8 2026-02-20        2026   February
2    A103         3 2026-03-10        2026      March
3    A104        10 2026-04-05        2026      April

# Section IV: Creating, Renaming, Dropping and Unique Values

19) Create this DataFrame as `products`.

```python
{
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Mouse'],
    'category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories'],
    'price': [450, 15, 25, 120, 18]
}
```

Create a new column named `stock` and assign the value `10` to every row.

In [20]:
products = pd.DataFrame({
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Mouse'],
    'category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories'],
    'price': [450, 15, 25, 120, 18]
})

products['stock'] = 10
products

    product     category  price  stock
0    Laptop  Electronics    450     10
1     Mouse  Accessories     15     10
2  Keyboard  Accessories     25     10
3   Monitor  Electronics    120     10
4     Mouse  Accessories     18     10

20) Rename the `stock` column to `units_available`.

In [21]:
products.rename( columns = {'stock' : 'units_available'}, inplace= True)
products

    product     category  price  units_available
0    Laptop  Electronics    450               10
1     Mouse  Accessories     15               10
2  Keyboard  Accessories     25               10
3   Monitor  Electronics    120               10
4     Mouse  Accessories     18               10

21) Delete the `units_available` column using `.drop()`.

In [22]:
products.drop(columns='units_available', inplace= True)
products

    product     category  price
0    Laptop  Electronics    450
1     Mouse  Accessories     15
2  Keyboard  Accessories     25
3   Monitor  Electronics    120
4     Mouse  Accessories     18

22) From `products`, display the unique values in `category` and then return the number of unique categories.

In [23]:
print("Unique categories:", products["category"].unique())
print("Number of unique categories:", products["category"].nunique())

Unique categories: <StringArray>
['Electronics', 'Accessories']
Length: 2, dtype: str
Number of unique categories: 2

23) Count how many times each value appears in the `category` column.

In [24]:
products['category'].value_counts()

category
Accessories    3
Electronics    2
Name: count, dtype: int64

24) Calculate the percentage distribution of `category`, rounded to 2 decimal places.

In [25]:
products["category"].value_counts(normalize=True).mul(100).round(2)

# "normalize=True" makes "value_counts()" return proportions instead of raw counts.

category
Accessories    60.0
Electronics    40.0
Name: proportion, dtype: float64

# Section V: Missing Values, Indexes and Duplicates

25) Create the DataFrame below as `customers`.

```python
{
    'customer_id': [1, 2, 3, 4, 4, 6],
    'name': ['Ali', 'Noor', 'Sara', 'Omar', 'Omar', 'Maya'],
    'age': [25, None, 31, 28, 28, None],
    'city': ['Manama', 'Riffa', None, 'Manama', 'Manama', 'Muharraq']
}
```

Count the null values in every column.

In [27]:
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 4, 6],
    'name': ['Ali', 'Noor', 'Sara', 'Omar', 'Omar', 'Maya'],
    'age': [25, None, 31, 28, 28, None],
    'city': ['Manama', 'Riffa', None, 'Manama', 'Manama', 'Muharraq']
})

customers.isnull().sum()

customer_id    0
name           0
age            2
city           1
dtype: int64

26) Calculate the percentage of null values in every column, rounded to 2 decimal places.

In [31]:
(customers.isnull().mean()*100).round(2)

customer_id     0.00
name            0.00
age            33.33
city           16.67
dtype: float64

27) Return the index values of rows where `age` is null as a Python list.

In [33]:
customers.index[customers['age'].isnull()].to_list()

[1, 5]

28) Remove rows where `city` is null, then reset the index so it starts from `0`.

In [34]:
customers = customers.dropna(subset=['city']).reset_index(drop=True)
customers

   customer_id  name   age      city
0            1   Ali  25.0    Manama
1            2  Noor   NaN     Riffa
2            4  Omar  28.0    Manama
3            4  Omar  28.0    Manama
4            6  Maya   NaN  Muharraq

29) Fill the missing values in `age` using the median age.

In [35]:
customers['age'] = customers['age'].fillna(customers['age'].median())
customers

   customer_id  name   age      city
0            1   Ali  25.0    Manama
1            2  Noor  28.0     Riffa
2            4  Omar  28.0    Manama
3            4  Omar  28.0    Manama
4            6  Maya  28.0  Muharraq

30) Count duplicate values in `customer_id`, then remove duplicates based on `customer_id` while keeping the first occurrence.

In [36]:
duplicate_count = customers['customer_id'].duplicated().sum()
print(duplicate_count)  

customers = customers.drop_duplicates(subset=['customer_id'], keep='first').reset_index(drop=True)

customers

1

   customer_id  name   age      city
0            1   Ali  25.0    Manama
1            2  Noor  28.0     Riffa
2            4  Omar  28.0    Manama
3            6  Maya  28.0  Muharraq